python -m intel_extension_for_pytorch.cpu.launch --node_id 0 finetune.py \
    --base_model 'llama-7b' \
    --data_path 'alpaca_data.json' \
    --output_dir './lora-alpaca' \
    --batch_size 512 \
    --micro_batch_size 64 \
    --num_epochs 3 \
    --learning_rate 1e-4 \
    --cutoff_len 512 \
    --val_set_size 2000 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj,v_proj]' \
    --train_on_inputs \
    --group_by_length
